import { ThemeProvider } from "@/components/theme-provider";

export const metadata = {
  title: {
    absolute: "",
    default: "Next.js tutorial - Codevolution",
    template: "%s | Coevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body>
          {children}
        </body>
      </ ThemeProvider>
    </html>
  );
}
