export const metadata = {
  title: {
    absolute: "",
    default: "Next.js tutorial - Codevolution",
    template: "%s | Coevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
          <p>Header</p>
        </footer>
      </body>
    </html>
  );
}
